### ISSUE TITLE
[Bug] - ARM docker images

### ISSUE THREAD

**Issue by haninator** [dqualizer/dqualizer#23]
## Describe the bug

there are no suitable arm images for
- [x] dqanalyzer-frontend 
- [x] ddd-autohaus
- [x] dqanalyzer-backend
- [x] grafana
- [x] dqexec

## To Reproduce

run the docker compose on an Apple Silicion Machine

## Expected behavior

To run fast

**Comment by franksn90** [comment]
@JenSeReal out of curiosity, because we talked about it here in the office: is there currently any activity on that issue?

**Comment by JenSeReal** [comment]
Partly implemented but not merged, e.g. https://github.com/dqualizer/dqtranslator/blob/multiarch/.github/workflows/docker-build-and-push.yml

**Comment by JenSeReal** [comment]
> @JenSeReal out of curiosity, because we talked about it here in the office: is there currently any activity on that issue?

@franksn90 Partly implemented but not merged, e.g. https://github.com/dqualizer/dqtranslator/blob/multiarch/.github/workflows/docker-build-and-push.yml

**Comment by franksn90** [comment]
This can be considered done now, @JenSeReal ?

**Comment by JenSeReal** [comment]
- [ ] dqtranslator does not have ARM images yet

**Comment by JenSeReal** [comment]
> This can be considered done now, @JenSeReal ?

Yes. dqexec is not on main yet, but can be closed
