### ISSUE TITLE
dqualizer auf der BMBF-Mittelstandskonferenz 2023 (Berlin)

### ISSUE THREAD

**Issue by GeorgiaKoenig** [dqualizer/dqualizer#35]
Als gefördertes Forschungsprojekt ist dqualizer eingeladen zur 
"BMBF-Mittelstandskonferenz 2023"; 

Dort können wir Präsenz in Form einer Postersession oder Standbetreuung zeigen.

Daten zur Konferenz: 
Wann? 21. und 22. November 2023; 
Wo? WECC Westhafen in Westhafenstr. 1, Sektor B, Halle 1, 13353 Berlin

**Comment by franksn90** [comment]
Akzeptanzkriterium: Georgias Script liegt im Sharepoint

**Comment by GeorgiaKoenig** [comment]
Script kann gefunden werden unter Sharepoint > 06_Konferenzen > 2023-11-20-BMBF-Mittelstand
